version: "3"

services:
    

    db:
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - "3307:3306"
        volumes:
          - $HOME/Ulwi/kumparan-test/article.sql:/article.sql

    redis:
        image: redis
        ports:
            - 6379:6379
        environment:
            - REDIS_PASSWORD=xyz

volumes:
    data01:
        driver: local